# This file was generated by GoReleaser. DO NOT EDIT.
cask "contract-cli" do
  version "1.26.1"

  on_macos do
    on_intel do
      sha256 "3fd9fa4c4d3784009d909bfc08ac21a02377d7ae8cc5886a5e835f5d31c22a4c"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
    on_arm do
      sha256 "9bad229994f8959ea0d246781b1bc75a702a8cc0ff222753a760f16f743e17d5"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "a92cbff854a13bde13e34d5b9693b74c3076c00532aa72f753a70419d1344c5b"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
    on_arm do
      sha256 "f91ae0202c9753e2b5b96604e641db201831eb4a544962dee40654ca55244d0f"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
  end

  name "contract-cli"
  desc "CLI tool for managing IBM Confidential Computing contracts and configurations"
  homepage "https://github.com/ibm-hyper-protect/contract-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openssl",
    ]

  binary "contract-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/contract-cli"]
    end
  end

  # No zap stanza required

end
