# This file was generated by GoReleaser. DO NOT EDIT.
cask "contract-cli" do
  version "1.23.1"

  on_macos do
    on_intel do
      sha256 "0e73b7623a10cc92156dcd6807836a9068498f7eddc8ff96cc43600ce21800d7"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
    on_arm do
      sha256 "0ce59e9d9fa7bb23d1ebeef247790abb57a98456f8bdbb244620379b04e9551e"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ed1699417a8af57e08c74fc9a5babc0a2cdc4177dc1277387d32bb450a9781c"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
    on_arm do
      sha256 "24aabcbc2fedf1dfb4619b25c40f5258f99ca0d34e3412eea5404cb975a63e11"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
  end

  name "contract-cli"
  desc "CLI tool for managing IBM Confidential Computing contracts and configurations"
  homepage "https://github.com/ibm-hyper-protect/contract-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openssl",
    ]

  binary "contract-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/contract-cli"]
    end
  end

  # No zap stanza required

end
