# This file was generated by GoReleaser. DO NOT EDIT.
cask "contract-cli" do
  version "1.36.2"

  on_macos do
    on_arm do
      sha256 "4982acdeb542a29d312c6b163066825ea63eee969afa73e8fce29a236e3c5219"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7232d6e584a03c19764063a9a3737bcab83b0a191e49b2c3342c22e5488fd339"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6257e920c27a3d6c20db2b9b2661c8be222dfda1fdb931474070ea9e9a014a54"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa680e31134506e5c7bf57d2c40b3037e19ab626b3186776d394091695cca4cb"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "contract-cli"
  desc "CLI tool for managing IBM Confidential Computing contracts and configurations"
  homepage "https://github.com/ibm-hyper-protect/contract-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openssl",
    ]

  binary "contract-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/contract-cli"]
    end
  end

  # No zap stanza required
end
