name: Question / Help
description: Ask a question or request help using contract-cli
title: "[Question]: "
labels: ["question", "help wanted"]
assignees:
  - Sashwat-K

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please provide details about your question to help us assist you better.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please verify these before asking your question
      options:
        - label: I have searched [existing issues](https://github.com/ibm-hyper-protect/contract-cli/issues) for similar questions
          required: true
        - label: I have read the [documentation](https://github.com/ibm-hyper-protect/contract-cli/blob/main/docs/README.md)
          required: true
        - label: I have checked the [README](https://github.com/ibm-hyper-protect/contract-cli/blob/main/README.md)
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation / Setup
        - Command Usage
        - Contract Generation
        - Certificate Management
        - Image Selection
        - Attestation Decryption
        - Network Configuration
        - Base64 Encoding
        - String Encryption
        - Error Troubleshooting
        - Best Practices
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: |
        I'm trying to...
        I need help with...
        How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / What You've Tried
      description: Provide context about what you're trying to accomplish and what you've already tried
      placeholder: |
        I'm working on: ...
        I've tried: ...
        I'm stuck because: ...
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Relevant Command
      description: If applicable, provide the CLI command you're asking about
      render: bash
      placeholder: |
        contract-cli command \
          --flag value \
          --option file.yaml

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform
      description: Which Hyper Protect platform are you working with?
      options:
        - HPVS (Hyper Protect Virtual Servers)
        - HPCR-RHVS (Hyper Protect Container Runtime)
        - HPCC-PeerPod (Confidential Container Peer Pods)
        - Not sure / General question
    validations:
      required: true

  - type: input
    id: cli-version
    attributes:
      label: CLI Version
      description: Output of `contract-cli --version` (if applicable)
      placeholder: "contract-cli version 1.7.0"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using? (if applicable)
      placeholder: "macOS 14.0, Ubuntu 22.04, Windows 11"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information that might help
      placeholder: Any other details that might be relevant...