// Copyright (c) 2025 IBM Corp.
// All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package decryptAttestation

import (
	"fmt"
	"log"
	"strings"

	"github.com/ibm-hyper-protect/contract-cli/common"
	"github.com/ibm-hyper-protect/contract-go/v2/attestation"
	"github.com/spf13/cobra"
)

const (
	ParameterName             = "decrypt-attestation"
	ParameterShortDescription = "Decrypt encrypted attestation records"
	ParameterLongDescription  = `Decrypt encrypted attestation records generated by Hyper Protect instances.

Attestation records are typically found at /var/hyperprotect/se-checksums.txt.enc
and contain cryptographic hashes for verifying workload integrity.`

	DecryptAttestFileInDescription   = "Path to encrypted attestation file (se-checksums.txt.enc)"
	DecryptAttestFlagDescription     = "Path to save decrypted attestation records"
	successMessageDecryptAttestation = "Successfully decrypted attestation records"
	InputFlagName                    = "in"
	OutputFlagName                   = "out"
	PrivateKeyFlagName               = "priv"
	PrivateKeyFlagDescription        = "Path to private key file for signing"
)

// ValidateInput - function to validate decrypt-attestation inputs
func ValidateInput(cmd *cobra.Command) (string, string, string, error) {
	encAttestPath, err := cmd.Flags().GetString(InputFlagName)
	if err != nil {
		return "", "", "", err
	}

	privateKeyPath, err := cmd.Flags().GetString(PrivateKeyFlagName)
	if err != nil {
		return "", "", "", err
	}

	decryptedAttestPath, err := cmd.Flags().GetString(OutputFlagName)
	if err != nil {
		return "", "", "", err
	}

	requiredFlags := map[string]string{
		"--in":   encAttestPath,
		"--priv": privateKeyPath,
	}

	var missing []string
	for flag, val := range requiredFlags {
		if val == "" {
			missing = append(missing, flag)
		}
	}

	if len(missing) > 0 {
		_ = cmd.Help()
		return "", "", "", fmt.Errorf(
			"Error: required flag(s) %s missing.",
			strings.Join(missing, ", "),
		)
	}

	return encAttestPath, privateKeyPath, decryptedAttestPath, nil
}

// DecryptAttestationRecords - function to decrypt attestation records
func DecryptAttestationRecords(encryptedAttestationRecordsPath, privateKeyPath string) (string, error) {
	if !common.CheckFileFolderExists(encryptedAttestationRecordsPath) {
		log.Fatal("The path to encrypted attestation records file doesn't exists")
	}
	if !common.CheckFileFolderExists(privateKeyPath) {
		log.Fatal("The path to private key doesn't exists")
	}

	encryptedChecksum, err := common.ReadDataFromFile(encryptedAttestationRecordsPath)
	if err != nil {
		return "", err
	}

	privateKey, err := common.ReadDataFromFile(privateKeyPath)
	if err != nil {
		return "", err
	}

	decryptedAttestationRecords, err := attestation.HpcrGetAttestationRecords(encryptedChecksum, privateKey)
	if err != nil {
		return "", err
	}

	return decryptedAttestationRecords, nil
}

// PrintDecryptAttestation - print decrypted attestation records or redirect to a file
func PrintDecryptAttestation(decryptedAttestationRecords, decryptedAttestationPath string) error {
	if decryptedAttestationPath != "" {
		err := common.WriteDataToFile(decryptedAttestationPath, decryptedAttestationRecords)
		if err != nil {
			return err
		}
		fmt.Println(successMessageDecryptAttestation)
	} else {
		fmt.Println(decryptedAttestationRecords)
	}

	return nil
}
