// Copyright (c) 2025 IBM Corp.
// All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package decryptAttestation

import (
	"fmt"
	"log"
	"strings"

	"github.com/ibm-hyper-protect/contract-cli/common"
	"github.com/ibm-hyper-protect/contract-go/v2/attestation"
	"github.com/spf13/cobra"
)

const (
	ParameterName             = "decrypt-attestation"
	ParameterShortDescription = "Decrypt encrypted attestation records"
	ParameterLongDescription  = `Decrypt encrypted attestation records generated by IBM Confidential Computing instances.

Attestation records are typically found at /var/hyperprotect/se-checksums.txt.enc
and contain cryptographic hashes for verifying workload integrity.`

	DecryptAttestFileInDescription   = "Path to encrypted attestation file (se-checksums.txt.enc, use '-' for standard input)"
	DecryptAttestFlagDescription     = "Path to save decrypted attestation records"
	successMessageDecryptAttestation = "Successfully decrypted attestation records"
	InputFlagName                    = "in"
	OutputFlagName                   = "out"
	PrivateKeyFlagName               = "priv"
	PrivateKeyFlagDescription        = "Path to private key file for signing"
	PasswordFlagName                 = "password"
	PasswordFlagDescription          = "Password for encrypted private key"
	SignatureFlagName                = "signature"
	SignatureFlagDescription         = "Path to signature file (se-signature.bin)"
	AttestationCertFlagName          = "attestation-cert"
	AttestationCertFlagDescription   = "Path to IBM attestation certificate file"
)

// ValidateInput - function to validate decrypt-attestation inputs
func ValidateInput(cmd *cobra.Command) (string, string, string, string, string, string, error) {
	encAttestPath, err := cmd.Flags().GetString(InputFlagName)
	if err != nil {
		return "", "", "", "", "", "", err
	}

	privateKeyPath, err := cmd.Flags().GetString(PrivateKeyFlagName)
	if err != nil {
		return "", "", "", "", "", "", err
	}

	decryptedAttestPath, err := cmd.Flags().GetString(OutputFlagName)
	if err != nil {
		return "", "", "", "", "", "", err
	}

	signaturePath, err := cmd.Flags().GetString(SignatureFlagName)
	if err != nil {
		return "", "", "", "", "", "", err
	}

	certPath, err := cmd.Flags().GetString(AttestationCertFlagName)
	if err != nil {
		return "", "", "", "", "", "", err
	}

	password, err := cmd.Flags().GetString(PasswordFlagName)
	if err != nil {
		return "", "", "", "", "", "", err
	}

	requiredFlags := map[string]string{
		"--in":   encAttestPath,
		"--priv": privateKeyPath,
	}

	var missing []string
	for flag, val := range requiredFlags {
		if val == "" {
			missing = append(missing, flag)
		}
	}

	if len(missing) > 0 {
		if len(missing) == 1 {
			err := fmt.Errorf("Error: required flag %s is missing.",
				strings.Join(missing, ", "))
			common.SetMandatoryFlagError(cmd, err)
		} else {
			err := fmt.Errorf("Error: required flags %s are missing.",
				strings.Join(missing, ", "))
			common.SetMandatoryFlagError(cmd, err)
		}
	}

	// Validate that if one of signature/cert is provided, both must be provided
	if (signaturePath != "" && certPath == "") || (signaturePath == "" && certPath != "") {
		log.Fatal("Error: --signature and --attestation-cert flags must be used together. Both are required or both should be omitted")
	}

	// Validate stdin input
	common.ValidateStdinInput(cmd, encAttestPath)

	return encAttestPath, privateKeyPath, decryptedAttestPath, signaturePath, certPath, password, nil
}

// DecryptAttestationRecords - function to decrypt attestation records
func DecryptAttestationRecords(encryptedAttestationRecordsPath, privateKeyPath, password string) (string, error) {
	var encryptedChecksum string
	var err error

	// Handle stdin input
	if encryptedAttestationRecordsPath == "-" {
		encryptedChecksum, err = common.ReadDataFromStdin()
		if err != nil {
			log.Fatal("Unable to read input from standard input")
		}
	} else {
		if !common.CheckFileFolderExists(encryptedAttestationRecordsPath) {
			log.Fatal("The path to encrypted attestation records file doesn't exists")
		}
		encryptedChecksum, err = common.ReadDataFromFile(encryptedAttestationRecordsPath)
		if err != nil {
			return "", err
		}
	}

	if !common.CheckFileFolderExists(privateKeyPath) {
		log.Fatal("The path to private key doesn't exists")
	}

	privateKey, err := common.ReadDataFromFile(privateKeyPath)
	if err != nil {
		return "", err
	}

	decryptedAttestationRecords, err := attestation.HpcrGetAttestationRecords(encryptedChecksum, privateKey, password)
	if err != nil {
		return "", err
	}

	return decryptedAttestationRecords, nil
}

// PrintDecryptAttestation - print decrypted attestation records or redirect to a file
func PrintDecryptAttestation(decryptedAttestationRecords, decryptedAttestationPath string) error {
	if decryptedAttestationPath != "" {
		err := common.WriteDataToFile(decryptedAttestationPath, decryptedAttestationRecords)
		if err != nil {
			return err
		}
		fmt.Println(successMessageDecryptAttestation)
	} else {
		fmt.Println(decryptedAttestationRecords)
	}

	return nil
}

// VerifySignatureAttestationRecords - function to verify signature of attestation records
func VerifySignatureAttestationRecords(attestationRecords, signaturePath, certPath string) error {
	// Read signature file (binary data)
	if !common.CheckFileFolderExists(signaturePath) {
		log.Fatal("The path to signature file doesn't exist")
	}
	signature, err := common.ReadDataFromFile(signaturePath)
	if err != nil {
		return err
	}

	// Read certificate file
	if !common.CheckFileFolderExists(certPath) {
		log.Fatal("The path to certificate file doesn't exist")
	}
	cert, err := common.ReadDataFromFile(certPath)
	if err != nil {
		return err
	}

	// Verify signature using contract-go library
	err = attestation.HpcrVerifySignatureAttestationRecords(attestationRecords, signature, cert)
	if err != nil {
		log.Fatal("Signature verification failed")
	}

	return nil
}
