package common

const (
	ContractCliName             = "contract-cli"
	ContractCliShortDescription = "Contract CLI: A CLI utility tool for Hyper Protect"
	ContractCliLongDescription  = `This tool helps to provision HPVS/RHVS on IBM Cloud and On Prem 

Refer github.com/ibm-hyper-protect/contract-cli for details on features`

	// Common

	FileInFlagName  = "in"
	FileOutFlagName = "out"

	DataFormatFlagName        = "format"
	DataFormatDefault         = "json"
	DataFormatJson            = "json"
	DataFormatYaml            = "yaml"
	DataFormatText            = "text"
	DataFormatFlagDescription = "Format in which the data needs to STDOUT or saved in file"

	PrivateKeyFlagName        = "priv"
	PrivateKeyFlagDescription = "Path to private key"

	VersionFlagName = "version"

	// Decrypt Attestation Records
	DecryptAttestParamName             = "decryptAttestation"
	DecryptAttestParamShortDescription = "Decrypt encrypted attestation records"
	DecryptAttestParamLongDescription  = `Decrypt encrypted attestation record generated by HPCR/RHVS under /var/hyperprotect/se-checksums.txt.enc`
	DecryptAttestFileInDefaultPath     = "build/se-checksums.txt.enc"
	DecryptAttestFileInDescription     = "Path to file that stores encrypted attestation records"
	DecryptAttestFlagDescription       = "Path to save the decrypted attestation records"

	// Get latest HPVS Image ID
	ImageParamName               = "image"
	ImageParamShortDescription   = "Get latest HPCR Image ID from IBM Cloud Image list"
	ImageParamLongDescription    = `Get latest HPCR image ID in IBM Cloud from IBM images JSON output from IBM Cloud API or CLI`
	IbmCloudJsonInputDescription = "Path to Terraform output or CLI or API result of image list"
	HpcrVersionFlagDescription   = "Get IBM Cloud Image details of specified HPCR version"
	HpcrImageFlagDescription     = "Path to store HPCR image details"

	// Download Encryption certificates
	DownloadCertParamName                = "downloadCertificates"
	DownloadCertParamShortDescription    = "Download encryption certificate"
	DownloadCertParamLongDescription     = `Download encryption certificate for HPCR from IBM Hyper Protect Repository`
	EncryptionCertVersionFlagDescription = "Versions of Encryption Certificates to download, Seperated by coma(,)"
	EncryptionCertsFlagDescription       = "Path to save the encryption certificates"

	// Base64
	Base64ParamName                  = "base64"
	Base64ParamShortDescription      = "Generate base64 of input"
	Base64ParamLongDescription       = `Generate base64 of input text`
	Base64InputFlagDescription       = "Input data that needs to be converted to string"
	Base64InputFormatFlagDescription = "Format of input data (default: text)"
	Base64OutputPathFlagDescription  = "Path to store Base64 output"
)
