package common

const (
	FileInFlagName  = "in"
	FileOutFlagName = "out"

	PrivateKeyFlagName        = "priv"
	PrivateKeyFlagDescription = "Path to private key"

	// Decrypt Attestation

	DecryptAttestParamName             = "decryptAttestation"
	DecryptAttestParamShortDescription = "Decrypt encrypted attestation records"
	DecryptAttestParamLongDescription  = `Decrypt encrypted attestation record generated by HPCR/RHVS.`

	DecryptAttestFileInDefaultPath = "build/se-checksums.txt.enc"
	DecryptAttestFileInDescription = "Path to file that stores encrypted attestation records"

	DecryptAttestFileOutDefaultPath = "build/se-checksums.txt"
	DecryptAttestFlagDescription    = "Path to save the decrypted attestation records"
)
